# PulumiAzureTemplateInfra - Set Secrets Script
Write-Host "🚀 Setting up PulumiAzureTemplateInfra Secrets" -ForegroundColor Green
Write-Host "===============================================" -ForegroundColor Green

# Check if pulumi is installed
if (-not (Get-Command pulumi -ErrorAction SilentlyContinue)) {
    Write-Host "❌ Pulumi CLI is not installed. Please install it first." -ForegroundColor Red
    exit 1
}

# Check if we're in a Pulumi project
if (-not (Test-Path "Pulumi.yaml")) {
    Write-Host "❌ Not in a Pulumi project directory. Please run this from your project root." -ForegroundColor Red
    exit 1
}

Write-Host "🔐 Setting up encrypted secrets..." -ForegroundColor Yellow
Write-Host "Using format: PulumiAzureTemplateInfra:SecretName" -ForegroundColor Yellow

# Core Infrastructure Secrets
Write-Host "Setting core infrastructure secrets..." -ForegroundColor Cyan
pulumi config set --secret PulumiAzureTemplateInfra:DockerRegistryPassword "YOUR_DOCKER_REGISTRY_PASSWORD"
pulumi config set --secret PulumiAzureTemplateInfra:SqlPassword "YOUR_SQL_PASSWORD"
pulumi config set --secret PulumiAzureTemplateInfra:BlobStorageKey "YOUR_BLOB_STORAGE_KEY"
pulumi config set --secret PulumiAzureTemplateInfra:FunctionStorageKey "YOUR_FUNCTION_STORAGE_KEY"

# Application Insights (can be retrieved from Azure or set manually)
Write-Host "Setting Application Insights secrets..." -ForegroundColor Cyan
pulumi config set --secret PulumiAzureTemplateInfra:AppInsightsConnectionString "InstrumentationKey=YOUR_INSTRUMENTATION_KEY;IngestionEndpoint=https://region.in.applicationinsights.azure.com/"

# External Services
Write-Host "Setting external service secrets..." -ForegroundColor Cyan
pulumi config set --secret PulumiAzureTemplateInfra:ExternalApiKey "YOUR_EXTERNAL_API_KEY"

# Event Grid & SignalR (will be generated by Azure, but can be set manually if needed)
Write-Host "Setting Event Grid and SignalR secrets..." -ForegroundColor Cyan
pulumi config set --secret PulumiAzureTemplateInfra:EventGridKey "YOUR_EVENT_GRID_ACCESS_KEY"
pulumi config set --secret PulumiAzureTemplateInfra:SignalRConnectionString "Endpoint=https://your-signalr.service.signalr.net;AccessKey=YOUR_ACCESS_KEY;Version=1.0;"

Write-Host ""
Write-Host "✅ Secrets Setup Complete!" -ForegroundColor Green
Write-Host "=========================" -ForegroundColor Green
Write-Host ""
Write-Host "📝 Remember to replace the placeholder values with your actual secrets:" -ForegroundColor Yellow
Write-Host "   - Docker Registry Password (from your container registry)" -ForegroundColor White
Write-Host "   - SQL Password (for your database server)" -ForegroundColor White
Write-Host "   - Storage Account Keys (from Azure Storage)" -ForegroundColor White
Write-Host "   - External API Keys (from your service providers)" -ForegroundColor White
Write-Host ""
Write-Host "🏗️  Ready to deploy:" -ForegroundColor Green
Write-Host "   1. Update secret values above with your actual values" -ForegroundColor White
Write-Host "   2. dotnet restore" -ForegroundColor White
Write-Host "   3. pulumi up" -ForegroundColor White
Write-Host ""
Write-Host "🎉 Your PulumiAzureTemplateInfra is ready!" -ForegroundColor Green